image: node:4.2.2@sha256:17982a679ddc0e0b8ccb5645dae7c33567640ea416f5dab0636573c9e11e0b01

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
   - npm install
   - node ./specs/start.js ./specs/async.spec.js
  tags:
    - docker

test_db:
  stage: test
  services:
    - postgres:9.5.0@sha256:e63199003939fc26d58e3a1f034db4e52604c4878192aa21b052feff1f3ae2a3
    - renovate/renovate:11.45.8@sha256:23c242f0b3fc48c2ae8403337b0c1344adaff760c1553c335639e646b37b96ba
  script:
   - npm install
   - node ./specs/start.js ./specs/db-postgres.spec.js
  tags:
    - docker
