image: node:4.9.0@sha256:92bc49b2e3c19c5ef38149bf789ecc1f4386211a2dca6650c59c5164244d4c92

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
   - npm install
   - node ./specs/start.js ./specs/async.spec.js
  tags:
    - docker

test_db:
  stage: test
  services:
    - postgres:9.5.0@sha256:e63199003939fc26d58e3a1f034db4e52604c4878192aa21b052feff1f3ae2a3
    - renovate/renovate:11.40.0@sha256:dec977dbbb38365a269088082396560fa34a712f696e89bfe89399073f9e7c48
  script:
   - npm install
   - node ./specs/start.js ./specs/db-postgres.spec.js
  tags:
    - docker
